/**
 * Created by Krzysiu on 27.03.2017.
 */
public abstract class Reagent {

    private Czastka czastka;
    private int stezenie;

    public Reagent(Czastka czastka, int stezenie) {
        this.czastka = czastka;
        this.stezenie = stezenie;
    }

    public Czastka getCzastka() {
        return czastka;
    }

    public void setCzastka(Czastka czastka) {
        this.czastka = czastka;
    }

    public int getStezenie() {
        return stezenie;
    }

    public void setStezenie(int stezenie) {
        this.stezenie = stezenie;
    }

    //automatically generated by IDE
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Reagent)) return false;

        Reagent reagent = (Reagent) o;

        if (stezenie != reagent.stezenie) return false;
        return czastka.equals(reagent.czastka);
    }

    //automatically generated by IDE
    @Override
    public int hashCode() {
        int result = czastka.hashCode();
        result = 31 * result + stezenie;
        return result;
    }

    public String toString() {
        return czastka.getNazwa() + " x " + getStezenie();
    }
}
